### ISSUE TITLE
mold setup and remove form

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#107]
![capture](https://cloud.githubusercontent.com/assets/11412673/7392648/c10fbc86-ee4e-11e4-9bb5-63e608fcb9b1.PNG)
![capture](https://cloud.githubusercontent.com/assets/11412673/7392679/f2a4c214-ee4e-11e4-8fe2-666b3fa32b47.PNG)
I do not know what is happening. Setup form did not require Mold last shot number, the pull down does not work. I cannot remove mold EA-1444.?????????

**Comment by nishant-njs** [comment]
"Mold Setup and Removal Form' updated as discussed over phone/email. Please test and close if resolved.

**Comment by philolsonjr** [comment]
Ok I tested the form and the "mold last shot number" is a look up field, and it does not work anymore.

**Comment by nishant-njs** [comment]
It does work. However, it is not populating now because we truncated the Orders table. See screenshot No 2 (this is the data from beta server). When the project goes live and new rows get added, this should work. You can also test by creating new setup if you want. We tested today on localhost (Screenshot No 1).

![1](https://cloud.githubusercontent.com/assets/7536874/7430349/ada5b104-f02f-11e4-8e66-e6996dd7e1ea.jpg)

![db](https://cloud.githubusercontent.com/assets/7536874/7430351/b63b844c-f02f-11e4-9ddf-c1e79fbd985d.jpg)

**Comment by philolsonjr** [comment]
You are showing the wrong data, I am looking at the last shot number, your screen shows nozzle change time???

**Comment by nishant-njs** [comment]
Here you go (tested on localhost and not beta server) -

![1](https://cloud.githubusercontent.com/assets/7536874/7467962/3a0423b8-f320-11e4-8487-893aa86e2834.jpg)

![2](https://cloud.githubusercontent.com/assets/7536874/7467964/3e2f53ae-f320-11e4-9107-58822d3a5b60.jpg)

![3](https://cloud.githubusercontent.com/assets/7536874/7467965/42737684-f320-11e4-984b-9ef312221ea3.jpg)

![4](https://cloud.githubusercontent.com/assets/7536874/7467967/44f77400-f320-11e4-9ed5-91e39e0ca875.jpg)

Please review and close the issue.

**Comment by philolsonjr** [comment]
If this not available to me how am I to test the database?

**Comment by nishant-njs** [comment]
You can create new setups and test accordingly.
