### ISSUE TITLE
Exit Button in Mold Setup And Removal Form - mini

### ISSUE THREAD

**Issue by nishant-njs** [nishant-njs/mold_maintenance_db#108]
See attached screenshots. Are we missing any logic?

1) Created a new Set-up - "CH-1976"
![1](https://cloud.githubusercontent.com/assets/7536874/7410008/b5b5795c-ef48-11e4-9b57-34b6ca6cfa17.jpg)

2) Selected CH-1976 from existing set-up, then clicked Start set-up, entered few values and closed the form
![2](https://cloud.githubusercontent.com/assets/7536874/7410015/c7078c7c-ef48-11e4-8d21-462a9c9cbe65.jpg)

3) Open the form again, selected CH-1976 from existing set-up, clicked End set-up and closed the form (note we did not enter Mold Last Shot Number)
![3](https://cloud.githubusercontent.com/assets/7536874/7410018/ce348202-ef48-11e4-9415-1e7e84a7c19b.jpg)

4) Open the form again, we cannot enter the Mold Last Shot Number since the created set-up is missing.
![4](https://cloud.githubusercontent.com/assets/7536874/7410023/d4af69ee-ef48-11e4-9926-eebccda7aa17.jpg)

5) Missing Mold Start Number in the database
![5](https://cloud.githubusercontent.com/assets/7536874/7410226/84768b72-ef4a-11e4-92cb-c11dc7113778.jpg)

**Comment by philolsonjr** [comment]
The magic happens when the go to remove mold button is pressed. That is were the data validation is done. This was how I could use the form three times. They were trained to go to the mold remove form. At one time they were one form but they kept forgetting to select the mold to remove, so they loaded and removed the same mold. You will note that I have the select list open when the form is opened, that done as the kept forgetting to select a mold and the data was lost.

**Comment by nishant-njs** [comment]
Noted.
