### ISSUE TITLE
SALVAGE PART DATA REPORT

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#121]
Missing data????

![capture](https://cloud.githubusercontent.com/assets/11412673/7617216/5ae436cc-f96f-11e4-97e5-e22a8c8388b0.PNG)

![capture](https://cloud.githubusercontent.com/assets/11412673/7617195/3a39d332-f96f-11e4-87eb-e0994980fbdb.PNG)

**Comment by nishant-njs** [comment]
No data is missing. The reason "Total Dollars" is empty is because the Salvage No is 0 or Null. And based on the formula set "Total Dollars" is Salvage No. * Earned Hours. See screenshots below.

1) "Total Dollars" is empty
![screenshot-a](https://cloud.githubusercontent.com/assets/7536874/7630693/52980cd6-fa56-11e4-85b6-fb20b8e44ac2.jpg)

2) Salvage Part No CHA-1186 is NULL (table data is from beta server)
![screenshot-b](https://cloud.githubusercontent.com/assets/7536874/7630694/54bd4b34-fa56-11e4-9fa9-ed58ca398954.jpg)

3) Similar functionality in Access
![screenshot-c](https://cloud.githubusercontent.com/assets/7536874/7630698/5752cc20-fa56-11e4-900b-ea832bec5e7b.jpg)

We've updated the report so it shows 0 when "Total Dollars" field is empty and corresponding red background.

**Comment by philolsonjr** [comment]
Data is missing, the report should have more than one part, see example.

**Comment by nishant-njs** [comment]
We have truncated the service table for testing. Currently, the service table in beta testing server is shown below. The part number CHA-1186 is the only part number while rest are NULL.

![1](https://cloud.githubusercontent.com/assets/7536874/7648815/a5e64c50-fb04-11e4-9445-6a989503b266.jpg)

Report:
![2](https://cloud.githubusercontent.com/assets/7536874/7648818/ac4e1348-fb04-11e4-8ff0-8bb6bdd7bb9a.jpg)

Please compare the database and report and let us know what's missing?
