### ISSUE TITLE
weekly setup review report

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#156]
![capture](https://cloud.githubusercontent.com/assets/11412673/11600764/72bf3640-9a94-11e5-9e93-23fdbcf317f2.JPG)

Mold remove form to prevent " " value for mold end number.

**Comment by nishant-njs** [comment]
We spent a lot of time debugging this issue, found the same in Access. See screenshot:
![156_1](https://cloud.githubusercontent.com/assets/7536874/11761352/8bc2473e-a0e5-11e5-9a92-f13b94ea0ca6.jpg)

We believe this happens when report is run after Mold Setup and before Mold Removal. Not sure though. Do share the answer.
