### ISSUE TITLE
data missing

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#162]
![capture](https://cloud.githubusercontent.com/assets/11412673/11636502/0eb6f2fa-9ce2-11e5-9cf7-fbaed42955bc.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11636514/1a71ca8e-9ce2-11e5-8f5c-9e6c119880f4.JPG)

Report shows three setups.
![capture](https://cloud.githubusercontent.com/assets/11412673/11636529/35c17e88-9ce2-11e5-9fe6-cbdc722076d1.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11636551/498fc00a-9ce2-11e5-84f5-a6399a166d13.JPG)

This report shows four completed???

**Comment by nishant-njs** [comment]
VISUAL REVIEW REPORT QUERY:
Visual report query is not showing record id 6719 because it has below condition in query. 
...INNER JOIN Engineers ON [Order Query All Fields].[Mold Setup Engineer 1] = Engineers.[ID Number]

Orders shown in visual report query has mold setup engineer with id = 2624, but the order 6719 has a different mold setup engineer with id = 5112 and so it is not getting displayed.

**Comment by philolsonjr** [comment]
?????  The query looks at the the order table and copies :
![capture](https://cloud.githubusercontent.com/assets/11412673/11844691/ba17582a-a3d5-11e5-92c6-e88bc54ba9c4.JPG)


![capture](https://cloud.githubusercontent.com/assets/11412673/11844755/051ad93c-a3d6-11e5-8c7b-cb9392fd1870.JPG)


So how can the data differ if it is the same field? There must be an error in your database somewhere..

**Comment by nishant-njs** [comment]
Fixed.

**Comment by nishant-njs** [comment]
We have updated source code with fixes, please recheck and confirm its working.
