### ISSUE TITLE
Form must have service ID number to properly identify cores for repair.

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#195]
![capture](https://cloud.githubusercontent.com/assets/11412673/11935092/7f870b66-a7cb-11e5-88db-5e6cf00536af.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11935105/931d7458-a7cb-11e5-9479-f357cfa50290.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11935170/0e746774-a7cc-11e5-8700-d5918bb276fd.JPG)

**Comment by nishant-njs** [comment]
In Access you generate auto increment unique Service ID when Resource drop-down is selected. Now that we have converted to web, this is not possible - the web assumes multiple users are logged in simultaneously. Code updated - we display Service ID when exit is clicked. Here is the screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/7536874/11954557/95e7b25c-a8cf-11e5-9a44-78b9bf148645.jpg)

**Comment by philolsonjr** [comment]
This change created an erroron the close service request. One cannot enter :date service request closed.

**Comment by nishant-njs** [comment]
Please share screenshot of the error.

**Comment by philolsonjr** [comment]
nothing to show, you cannot get the system to give you a date.

**Comment by nishant-njs** [comment]
Sorry, please elaborate on the issue. Don't understand if it's an error or you not able to update something. If so, what is it?

**Comment by philolsonjr** [comment]
Use the form to close a service request, it will not close because the closed date will not fill. Try it you will see the error.

**Comment by nishant-njs** [comment]
The issue title says - "Form must have service ID number to properly identify cores for repair." You posted 3 screenshots of 2 forms (new service request and close service request) - we assumed once a service request is created, operator should know the auto generated service id so they can use to close the service. To which we added a pop-up displaying the service id before redirecting to switchboard. To which you commented that "This change created an erroron the close service request. One cannot enter :date service request closed." In your last comment you said - "Use the form to close a service request, it will not close because the closed date will not fill. Try it you will see the error.".

Create a new service request and close a service request are two different forms. We did not make any changes to "close service request form". Importantly, the changes we made in create a new service request (display service id) will not affect the other form.

For unknown reason, the form in Access errors out.
![1](https://cloud.githubusercontent.com/assets/7536874/11972177/7c007938-a96e-11e5-86ac-21324fcf4caa.jpg)

We tested on our side. Here are the screenshots:
1) Created a new service request
![2](https://cloud.githubusercontent.com/assets/7536874/11972245/9ca87018-a96f-11e5-83ab-002b931908a0.jpg)

2) Selected service id generated in 1) and entered all the details
![3](https://cloud.githubusercontent.com/assets/7536874/11972254/ad72c074-a96f-11e5-883e-6363797ef36c.jpg)

3) Close service request
![4](https://cloud.githubusercontent.com/assets/7536874/11972259/b3318608-a96f-11e5-8997-acd4bb502995.jpg)

**Comment by philolsonjr** [comment]
![capture](https://cloud.githubusercontent.com/assets/11412673/12401208/a2d74812-bdea-11e5-9987-c5f75760fb9e.JPG)


Form will not close. when a date is selected from pop up it does not fill in the date service completed, it just sits on the screen no error no nothing.

**Comment by nishant-njs** [comment]
Sometime the browser fails to load css/js files due to network issues. Please reload the page.
