### ISSUE TITLE
setup schedule report

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#84]
![capture](https://cloud.githubusercontent.com/assets/11412673/7230736/44ae0de2-e736-11e4-9b92-112295152b61.PNG)
Note report still shows same setup twice.
Only one request for this mold and was created today.
Each setup MUST be on a single line, otherwise report will not fit on screen.

**Comment by nishant-njs** [comment]
"Note report still shows same setup twice. Only one request for this mold and was created today." - Correct me if I am wrong - this particular issue was created, discussed and closed. See Issue No.: #19 and Issue No.: #25 .

" Each setup MUST be on a single line, otherwise report will not fit on screen." - this is pending.

**Comment by philolsonjr** [comment]
![capture](https://cloud.githubusercontent.com/assets/11412673/7252402/48de3a4e-e7fa-11e4-94bc-6298b4cd6f66.PNG)
Form is still using two lines, please follow text  and setup criteria in sample database. Two lines will not display what we need in the shop.

**Comment by nishant-njs** [comment]
We've updated the code - each row will display in one line similar to access. Please test and close the issue if resolved.
